[package]
name = "ethash"
description = "An Apache-licensed Ethash implementation."
version = "0.4.1"
authors = ["Wei Tang <hi@that.world>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
ethereum-types = { version = "0.12", default-features = false, features = ["rlp"] }
primitive-types = { version = "0.10", default-features = false, features = [
  "rlp",
] }
rlp = { version = "0.5", default-features = false }
byteorder = { version = "1", default-features = false }
sha3 = { version = "0.10", default-features = false }
sha2 = { version = "0.8", default-features = false, optional = true }
lazy_static = { version = "1.4", default-features = false, optional = true, features = ["spin_no_std"] }

tiny-keccak = { version = "2.0.1", features = ["keccak"], optional = true }
num_cpus = { version = "1", optional = true }
rayon = { version = "1.5", optional = true }
parking_lot = { version = "0.11", optional = true }

[dev-dependencies]
hex = { version = "0.4", default-features = false }
hex-literal = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
humantime = "2.0.1"

[features]
default = ["std", "withproofs"]
withproofs = [
  "tiny-keccak",
  "sha2",
  "lazy_static",
]
std = [
  "ethereum-types/std",
  "rlp/std",
  "byteorder/std",
  "sha3/std",
  "num_cpus",
  "rayon",
  "parking_lot",
]
